# UE4_Materials
caidu UE4.25材质
2020-06-18
:toc:

## 1. Content/Materials 材质表达式

### 1.1. 光照半透明？

### 1.2. M_AtmosphericFogColor 大气表达式
用来在全局空间中的任意位置，查询关卡的大气雾的当前颜色。如果没有向其输送全局位置，那么将使用相关像素的全局位置。这在您需要让材质逐渐融入远方的雾颜色时非常有用。

### 1.3. M_Color 颜色表达式
对颜色输入执行操作的表达式。
- Desaturation（去饱和度） 表达式对其输入进行去饱和，即根据特定百分比将其输入的颜色转换为灰色阴影。

### 1.4. M_Constant 常量表达式
输出值在编辑器中设置后或在游戏开始时设置后通常保持不变的表达式。

- Constant（常量）表达式输出单个浮点值。这是最常用的表达式之一，并可连接到任何输入，而不必考虑该输入所需的通道数。例如，如果您将一个常量连接到需要 3 个矢量的输入，那么该常量值将用于全部 3 个元素。提供单个数值时，使用说明区域中的小三角形图标来折叠节点可能非常有用。
- Constant2Vector（常量 2 矢量）表达式输出双通道矢量值，即输出两个常量数值。
- Constant3Vector（常量 3 矢量）表达式输出三通道矢量值，即输出三个常量数值。您可以将 RGB 颜色看作 Constant3Vector（常量 3 矢量），其中每个通道都被赋予一种颜色（红色、绿色、蓝色）。
- Constant4Vector（常量 4 矢量）表达式输出四通道矢量值，即输出四个常量数值。您可以将 RGBA 颜色看作 Constant4Vector（常量 4 矢量），其中每个通道都被赋予一种颜色（红色、绿色、蓝色、alpha）。
- DistanceCullFade（距离剔除消退） 表达式输出一个从黑色逐渐消退到白色的标量值，并可用于使对象进入剔除距离后逐渐消退。请注意，它不会使对象淡出。
- ParticleColor（粒子颜色） 表达式绑定到给定粒子的当前颜色。这必须插入到适当的信道（自发光颜色）。基于在 级联（Cascade粒子系统） 中定义的任何每粒子颜色数据
- ParticleDirection（粒子方向） 表达式逐个粒子输出Vector3(RGB)数据，表示给定粒子当前运动的方向。
- ParticleMotionBlurFade（粒子动态模糊淡出） 表达式输出一个值，该值表示由于动态模糊导致的粒子上的淡出量。值为1表示无模糊，黑色代表完全模糊。
- ParticleRadius（粒子半径） 表达式单独输出每个粒子的半径（采用虚幻单位）。例如，一旦半径达到某个点，就可以对材质进行更改。
- ParticleRelativeTime（粒子相对时间） 表达式输出0到1之间的数字，表示粒子的年龄，0表示出生时刻，1表示死亡时刻。
- Particle Size（粒子大小） 表达式输出粒子sprite的X和Y大小。这可以用来驱动材质的某些方面。
- ParticleSpeed（粒子速度） 输出正在运动的每个粒子的当前速度，单位为每秒虚幻单位。
- PerInstanceFadeAmount（按实例消退量）表达式输出一个浮点值，该值与应用于实例化静态网格（例如植物叶子）的消退量相关联。它是常量，但对于网格的每个实例，可以是不同的数值。
- PerInstanceRandom（按实例随机）表达式按材质所应用于的静态网格实例输出不同的随机浮点值。InstancedStaticMeshComponent（实例化静态网格组件）用于为实例设置随机浮点值，这个值将公开，以便可用于任何期望的内容（例如，窗外的随机光照水平）。它是常量，但对于网格的每个实例有所不同。
- Time（时间）节点用来向材质（例如，Panner（平移） 、Cosine（余弦） 或其他时间相关操作）添加经历时间。
- TwoSidedSign（双面符号）表达式适合在双面定制照明材质的背面翻转法线，以便与冯氏（Phong）明暗处理算法匹配。+1 表示双面材质的正面，-1 表示背面。
- VertexColor（顶点颜色）表达式是材质的访问点，用于访问影响精灵粒子发射器的颜色模块的输出。
- ViewProperty（视图属性） 表达式输出依赖于视图的常量属性，例如视野或渲染目标大小。要访问的视图属性可配置，并且，输出类型取决于所配置的待访问属性。
- PrecomputedAOMask（预先计算的 AO 蒙版）节点用来访问材质中光照系统计算的环境光遮蔽 (AO)， 这可能很适合于过程式纹理贴图，或者在老化效果及尘埃随时间推移而缓慢积累的区域加入老化效果及尘埃。

### 1.5. M_Coordinates 坐标表达式
对纹理坐标、可用作纹理坐标的输出值或者用来修改纹理坐标的输出值执行操作的表达式。

- ActorPositionWS 输出矢量3(RGB)数据，该数据表示对象在世界场景空间中的位置以及其上的材质。
- CameraWorldPosition 表达式输出三信道矢量值，该值表示摄像机在世界场景空间中的位置。
- LightmapUVs（光照贴图 UV）表达式以双通道矢量值形式输出光照贴图 UV 纹理坐标。如果无法获得光照贴图 UV，那么将输出双通道矢量值 (0,0)。
- ObjectOrientation 表达式输出对象的世界场景向上矢量。换言之，对象的局部正z轴正指向此方向。
- ObjectPositionWS 表达式输出对象边界的世界场景空间中心位置。例如，这对于为植物创建球形照明很有用。
- ObjectRadius（对象半径）输出给定对象以 Unreal 单位计的半径值。系统会对比例缩放加以考虑，并且对于每个对象，结果可能是唯一的。
- Panner（平移）表达式输出可用于创建平移（或移动）纹理的 UV 纹理坐标。
- 粒子位置WS（ParticlePositionWS） 表达式输出代表世界场景空间中每个单独粒子位置的Vector3(RGB)数据。
- PixelNormalWS 表达式根据当前法线输出矢量数据，该数据表示像素所面对的方向。
- Rotator（旋转）表达式以双通道矢量值形式输出 UV 纹理坐标，该矢量值可用来创建旋转纹理。
- SceneTexelSize（场景纹素大小）表达式允许按纹素大小进行偏移，正如您使用 SceneColor（场景颜色）
- SceneDepth（场景深度）表达式时执行的偏移操作。这对于在多分辨率系统中检测边缘十分有用，因为不进行此计算时，您就必须使用较小的静态值，从而导致分辨率较低时结果不一致。
- ScreenPosition（屏幕位置）表达式输出当前所渲染像素的屏幕空间位置。
- TextureCoordinate（纹理坐标）表达式以双通道矢量值形式输出 UV 纹理坐标，从而允许材质使用不同的 UV 通道、指定平铺以及以其他方式对网格的 UV 执行操作。
- VertexNormalWS 表达式输出世界场景空间顶点法线。它只能用于在顶点着色器中执行的材质输入，例如WorldPositionOffset。该表达式对于设置网格体增大或缩小很有用。请注意，沿法线偏移位置会导致几何图形沿UV缝隙拆分。
- ViewSize（视图大小）表达式输出一个 2D 矢量，以给出当前视图的大小（以像素为单位）。这对于使材质根据当前屏幕分辨率产生各种变化来说非常有用。
- WorldPosition（全局位置）表达式输出当前像素在全局空间中的位置。要实现可视化，只需将输出连接到“自发光”（Emissive）

### 1.6. M_Depth 深度表达式
处理所渲染像素的深度的表达式。

- DepthFade（深度消退）表达式用来隐藏半透明对象与不透明对象相交时出现的不美观接缝。
- PixelDepth（像素深度）表达式输出当前所渲染像素的深度，即从摄像机开始计算的距离。
- SceneDepth（场景深度）表达式输出现有的场景深度。这类似于 PixelDepth（像素深度） ，但是 PixelDepth（像素深度）只能在当前所绘制像素处进行深度取样，而 SceneDepth（场景深度）可以在 任何位置 进行深度取样。只有半透明材质可以利用 SceneDepth（场景深度）。

### 1.7. M_Custom 自定义表达式
允许您编写自定义 HLSL 着色器代码，这些代码可对任意数量的输入执行操作，并输出操作结果。

### 1.8. M_Font 字体表达式
对字体资产进行取样和输出的表达式。

- FontSample（字体取样）表达式允许您以常规 2D 纹理形式，从字体资源中取得纹理页面样本。字体的阿尔法通道将包含字体轮廓值。您只能指定有效的字体页面。
- FontSampleParameter（字体取样参数）表达式提供了一种在材质实例常量中公开基于字体的参数的方法，这使您可以在不同实例中轻松使用不同的字体。字体的阿尔法通道将包含字体轮廓值。您只能指定有效的字体页面。

### 1.9. 材质函数表达式？
用来创建或执行材质函数的表达式。

- FunctionInput（函数输入）表达式只能放在材质函数中，用于在该函数中定义该函数的某个输入。
- FunctionOutput（函数输出）表达式只能放在材质函数中，用于在该函数中定义该函数的某个输出。
- MaterialFunctionCall（材质函数调用）表达式允许您使用来自另一材质或函数的外部 材质函数 。这个外部函数的输入及输出节点将变成函数调用节点的输入和输出。如果放置其中某个表达式时在 内容浏览器 中选中了某个材质函数，那么将自动指派该函数。
- StaticBool（静态布尔值）表达式用来为函数内的静态布尔函数输入提供默认布尔值。此节点不会在任何内容之间切换，因此必须与 StaticSwitch（静态开关）节点配合使用。
- StaticSwitch（静态开关）表达式的工作方式与 StaticSwitchParameter（静态开关参数）类似，但是它仅实现开关，而不会创建参数。
- TextureObject（纹理对象）表达式用来为函数内的纹理函数输入提供默认纹理。此节点不会对该纹理进行实际取样，因此必须与“纹理取样”（TextureSample）节点配合使用。

### 1.10. 地形表达式？

### 1.11. 材质属性表达式?
这些表达式节点使您能够分隔或组合各种材质属性，这在创建分层材质时特别有用。

- Break Material Attributes
- Make Material Attributes

### 1.12. M_Math 数学表达式
对一个或多个输入执行数学运算的表达式。

- Abs 是数学术语“绝对值（absolute value）”的缩写。Abs表达式输出它接收到的输入的绝对值或无符号值。本质上，这意味着它通过去掉负号把负数变成正数，而正数和零保持不变。
- Add 表达式接受两个输入，将它们相加并输出结果。
- AppendVector（追加矢量）表达式允许您将通道组合在一起，以创建通道数比原始矢量更多的矢量。例如，您可以使用两个 常量 值并进行追加，以建立双通道 Constant2Vector（常量 2 矢量） 值。这有助于将单个纹理中的通道重新排序，或者将多个灰阶纹理组合成一个 RGB 彩色纹理。
- Arccosine 表达式输出反余弦函数。
- ArccosineFast 表达式输出反余弦函数的近似值，计算起来比更精确的Arccosine 表达式更快。输入必须介于-1与1之间。
- Arcsine 表达式输出反正弦函数。
- ArcsineFast 表达式输出反正弦函数的近似值，计算起来比更精确的Arcsine 表达式更快。输入必须介于-1与1之间。
- Arctangent 表达式输出反正切函数。
- Arctangent2 表达式输出x/y的反正切，其中输入符号用于确定象限。
- ArctangentFast 表达式输出反正切函数的近似值，计算起来比更精确的Arctangent 表达式更快。
- Arctangent2Fast 表达式输出X/Y的反正切的近似值，其中输入符号用于确定象限。比起Arctangent2 表达式，它计算得更快，但精确度较低。
- Ceil 表达式接受值，将它们向 上 舍入到下一个整数，并输出结果。
- Clamp 表达式接受一个或多个值，并将它们约束到由最小值和最大值定义的指定范围内。如果最小值为0.0，最大值为0.5，则意味着结果值永远不会小于0.0，且永远不会大于0.5。
- ComponentMask（分量蒙版）表达式允许从输入中选择通道（R、G、B 和/或 A）的特定子集以传递到输出。尝试传递输入中不存在的通道将导致错误，除非输入是单个常量值。在这种情况下，会将单个值传递到每个通道。选择传递的当前通道将显示在表达式的标题栏中。
- Cosine 表达式在[0, 1]的输入范围和[-1, 1]的输出范围上反复输出余弦波的值。此表达式最常用于通过将一个时间 表达式与其输入连接来输出连续的振荡波形，但它也可以用于在世界场景空间或屏幕空间或任何其他需要连续、平滑循环的应用中创建波纹。
- CrossProduct 表达式计算两个三通道矢量值输入的交叉乘积，并输出产生的三通道矢量值。假定空间中有两个矢量，则交叉乘积是一个同时垂直于两个输入的矢量。
- Divide 表达式取两个输入，将第一个输入除以第二个输入，并输出值。
- DotProduct 表达式计算点积，点积可以描述为一个矢量投影到另一个矢量上的长度，也可以描述为两个矢量之间的余弦乘以它们的幅值。许多技术使用这种算法来计算衰减。DotProduct要求两个矢量输入具有相同数量的通道。
- Floor 表达式接受值，将它们向 下 舍入到上一个整数，并输出结果
- Fmod 表达式返回两个输入的除法运算的浮点余数。被除数（输入“A”）可以是任何值，但负被除数将导致负结果。除数（第二个输入）不应为零，因为这意味着要除以零，但是除数是负数还是正数并不会影响结果。它的常见的用例是制作一种材质，使其亮度上升到最大值，然后在下一帧中立即下降到最小值，然后再次开始向最大值攀升。
- Frac 表达式接受值并输出这些值的小数部分。换句话说，对于输入值“X”，结果是“X - X的整数部分”。输出值将从0到1不等，包括下限值，但不包括上限值。
- If 表达式比较两个输入，然后根据比较的结果传递其他三个输入值中的一个。两个比较的输入都必须是单一浮点值。
- LinearInterpolate（线性插值） 表达式根据用作蒙版的第三个输入值，在两个输入值之间进行混合。您可以将其想像成用于定义两个纹理之间的过渡效果的蒙版，例如Photoshop中的层蒙版。
- Logarithm10 节点返回输入值的以10为底的对数，也称为公共对数。也就是说，如果取一个基数为10的值，并将其提高到该表达式返回的数字的幂，就会得到输入值。
- Logarithm2节点返回输入值的以2为底的对数。也就是说，如果取一个基数为2的值，并将其提高到该表达式返回的数字的幂，就会得到输入值。
- Max 表达式接受两个输入，并输出其中较高的一个。当您使用该节点和颜色输入时，结果类似于Photoshop中的 变亮 图层混合模式。
- Min 表达式接受两个输入，输出两个输入中较小的一个。当您使用该节点和颜色输入时，结果类似于使用Photoshop中的 变暗 图层混合模式。
- Multiply 表达式接受两个输入，将它们相乘，然后输出结果。当您将颜色值作为输入传递时，结果类似于Photoshop中的 正片叠底 图层混合模式的结果。
- Normalize 表达式计算并输出其输入的归一化值。归一化矢量（也称“单位矢量”）的整体长度为1.0。这意味着输入的每个分量都除以矢量的总大小（长度）。
- OneMinus 表达式接受输入值“X”并输出“1 - X”。此操作逐通道执行。
- Power 表达式接收两个输入：基值(Base)和指数(Exp)。它将基值提高到指数的幂，并输出结果。换句话说，它返回 Base 乘以自身 Exp 次。
- Round 表达式将输入值舍入为最接近的整数。如果输入值的小数部分为0.5或更大，则将输出值向上舍入。否则将输出值向下舍入。
- Saturate 节点将值限定在0与1之间。小于0的值被提升到0；大于1的值降低为1；0到1之间（包括0和1在内）的值保持不变。在大多数现代图形硬件上，Saturate的指令成本几乎是免费的，所以您可以在任何时候使用该节点来将输入或输出值限制在0到1之间，而不影响您的材质的性能。
- Sign 节点指示数字输入是负数、正数还是恰好为0。
- Sine 表达式在[0, 1]的输入范围和[-1, 1]的输出范围上反复输出正弦波的值。它与Cosine 表达式的输出之间的区别是输出波形被四分之一的周期所抵消，这意味着“Cos(X)”等于“Sin(X + 0.25)”。此表达式最常用于通过将一个时间 表达式与其输入连接来输出连续的振荡波形，但它也可以用于在世界场景空间或屏幕空间或任何其他需要连续、平滑循环的应用中创建波纹。
- SquareRoot 表达式输出输入值的平方根。如果应用于矢量，则每个分量将分别处理。
- Subtract 节点接受两个输入，将第一个输入减去第二个输入，然后输出差值。
- Tangent 节点输出指定值的正切值。
- Truncate 节点通过丢弃小数部分而保留整数部分来截断值。

### 1.13. M_Parameter 参数表达式
这类表达式向材质实例公开属性，以便在子实例中覆盖或在运行时修改。

- CollectionParameter（集合参数）表达式用来引用“参数集合”资产。这些是可以由许多不同资产（例如材质和蓝图等等）轻松重复使用的参数组。
- DynamicParameter（动态参数）表达式为粒子发射器提供管道，以便将最多四个要以任意方式处理的值传递给材质。这些值是通过放置在发射器上的 ParameterDynamic 模块在 Cascade 中设置的。
- FontSampleParameter（字体取样参数）表达式提供了一种在材质实例常量中公开基于字体的参数的方法，这使您可以在不同实例中轻松使用不同的字体。字体的阿尔法通道将包含字体轮廓值。您只能指定有效的字体页面。
- ScalarParameter（标量参数）表达式输出单个浮点值 (Constant（常量） )，这个值可在材质实例中访问和更改，或者由代码快速访问和更改。
- StaticBoolParameter（静态布尔参数）的工作方式类似于 StaticSwitchParameter（静态开关参数），但是它仅创建一个布尔参数，而不实现开关。
- StaticSwitchParameter（静态开关参数）表达式接收两个输入，并且在参数值为 true 时输出第一个输入的值，否则输出第二个输入的值。
- StaticComponentMaskParameter（静态分量蒙版参数）表达式的行为就像是普通的组件蒙版一样，只不过实例可设置蒙版值。
- VectorParameter（矢量参数）表达式与 Constant4Vector（常量 4 矢量） 完全相同，只不过它是可在材质实例中以及通过代码来修改的参数。VectorParameter（矢量参数）的一个好处是，它的值可使用取色器来设置。
- TextureObjectParameter（纹理对象参数）表达式定义一个纹理参数并输出纹理对象，以便在调用具有纹理输入的函数的材质中使用。此节点不会对该纹理进行实际取样，因此必须与“纹理取样”（TextureSample）节点配合使用。
- TextureSampleParameter2D（纹理取样参数 2D）表达式与 TextureSample（纹理取样）完全相同，只不过它是可在材质实例中以及通过代码来修改的参数。
- TextureSampleParameterSubUV 表达式与ParticleSubUV 一致，除了它是一个参数，可以在材质实例中修改，也可以通过代码修改。
- TextureSampleParameterCube（纹理取样参数立方体）表达式与 TextureSample（纹理取样）完全相同，只不过它只接受立方体贴图，并且是可在材质实例中以及通过代码来修改的参数。
- TextureSampleParameterMovie（纹理取样参数电影）表达式与 TextureSample（纹理取样）完全相同，只不过它只接受电影贴图（Bink 电影），并且是可在材质实例中以及通过代码来修改的参数。

### 1.14. M_Particle 粒子表达式
用于创建要应用于粒子系统中的发射器的材质表达式。这里有很多和常量表达式重复了，以下会标记见常量表达式。

- DynamicParameter（动态参数）表达式为粒子发射器提供管道，以便将最多四个要以任意方式处理的值传递给材质。这些值是通过放置在发射器上的 ParameterDynamic 模块在 Cascade 中设置的。
- ParticleColor（粒子颜色） 见常量表达式
- ParticleDirection（粒子方向） 见常量表达式
- ParticleMacroUV 表达式输出UV纹理坐标，可用于以连续的方式将任何二维纹理映射到整个粒子系统，这意味着纹理将在粒子之间无缝连接。
- ParticleMotionBlurFade（粒子动态模糊淡出） 见常量表达式
- ParticlePositionWS（粒子位置WS） 见常量表达式
- ParticleRadius（粒子半径） 见常量表达式
- ParticleRelativeTime（粒子相对时间） 见常量表达式
- Particle Size（粒子大小） 见常量表达式
- ParticleSpeed（粒子速度） 见常量表达式
- SphericalParticleOpacity（球形粒子不透明度） 表达式创建程序不透明映射，以使sprite粒子呈现球形。这比创建一个类似效果的纹理地图要简单得多。
- ParticleSubUV 表达式用于将纹理的子图像渲染到粒子。ParticleSubUV类似于flipbook，不同的是ParticleSubUV允许在级联（Cascade）中操作纹理动画。
- TextureSampleParameterSubUV 表达式与ParticleSubUV 一致，除了它是一个参数，可以在材质实例中修改，也可以通过代码修改。

### 1.15. M_Texture 纹理表达式
对纹理进行取样和输出的表达式。

- FontSample（字体取样） 见字体表达式
- FontSampleParameter（字体取样参数） 见字体表达式
- SceneColor 表达式输出现有的场景颜色。
- SpriteTextureSampler 要创建定制Sprite材质，可以复制一个现有的Sprite材质，也可在 内容浏览器 中创建新材质。渲染Sprite时，在Sprite资源中定义的纹理将输送到材质中任何具有“SpriteTexture”名称的纹理参数。可以放置SpriteTextureSampler节点以自动完成此操作。
- TextureObject（纹理对象） 见材质函数表达式
- TextureSample 表达式输出纹理中的颜色值。此纹理可以是常规Texture2D（包括法线贴图）、立方体贴图或电影纹理。
- TextureProperty 用于公开你选择的纹理属性，例如纹理大小或纹素大小。
- ParticleSubUV 见粒子表达式
- TextureObjectParameter （纹理对象参数） 见参数表达式
- TextureSampleParameter2D（纹理取样参数 2D）见参数表达式
- TextureSampleParameterSubUV 见粒子表达式，参数表达式
- TextureSampleParameterCube（纹理取样参数立方体） 见参数表达式

### 1.16. M_Utility 实用表达式
对一个或多个输入执行各种实用运算的表达式。

- AntialiasedTextureMask（抗锯齿纹理蒙版） 表达式允许您使用软（抗锯齿）过渡蒙版来创建材质。此蒙版可用来在两个复杂材质属性之间混合，或者使alpha混合材质淡出（适合与“软屏蔽”配合使用）。
- BlackBody（黑体） 表达式用来在材质中模拟黑体辐射 。用户输入开氏温度，产生的颜色和强度可用来驱动“底色”（Base Color）和“自发光”（Emissive）值，以获得在物理上准确的结果。
- BumpOffset（凹凸贴图偏移） 是虚幻引擎4术语，就是通常所谓的“视差贴图”。BumpOffset表达式可以使材质产生深度错觉，而不需要额外的几何体。BumpOffset材质使用灰阶_高度贴图_来提供深度信息。高度贴图中的值越亮，材质的“凸出”效果越明显；当摄像机在表面上移动时，这些区域将产生视差（移位）。高度贴图中较暗的区域将显得“距离较远”，其移位程度最小。
- ConstantBiasScale（常量偏差比例） 表达式接收输入值，加上偏差值，然后乘以比例缩放系数并输出结果。例如，要将输入数据从[-1,1] 转换到[0,1]，请使用偏差值1.0和比例缩放系数0.5。
- DDX 表达式公开DDX导数计算，这是像素着色器计算中使用的一项GPU硬件功能。
- DDY 表达式公开DDX导数计算，这是像素着色器计算中使用的一项GPU硬件功能。
- DepthFade（深度消退） 表达式用来隐藏半透明对象与不透明对象相交时出现的不美观接缝。
- DepthOfFieldFunction（视野深度函数） 表达式使美工能够控制当视野深度使材质模糊时，材质所发生的情况。它输出介于0与1之间的值，其中0代表“清晰”，而1代表“完全模糊”。例如，这对于在纹理的清晰版本与模糊版本之间进行插值非常有用。“深度”（Depth）输入允许您使用其他计算来覆盖场景视野深度计算所产生的现有结果。
- Desaturation（去饱和度） 表达式对其输入进行去饱和度，即根据特定百分比将其输入的颜色转换为灰色阴影。
- Distance（距离） 表达式计算两个点/颜色/位置/矢量之间的欧氏距离，并输出结果值。此表达式可作用于单分量、双分量、三分量和四分量矢量，但此表达式的两个输入必须具有相同数目的通道。
- DistanceFieldGradient（距离场梯度） 材质表达式节点进行规范化后，将输出对象在距离场中的X,Y,Z移动方向。 这使DistanceFieldGradient材质表达式节点非常适合于需要模拟液体流的材质。
- DistanceToNearestSurface（与最近表面的距离） 材质表达式节点允许材质对“全局距离场”关卡中的任何点进行取样。 这个材质表达式将输出从距离场到场景中最近遮挡体的带符号距离（以全局空间单位计）。
- FeatureLevelSwitch（功能级别开关） 节点允许您建立简化的材质，以用于功能不太强大的设备。
- Fresnel（菲涅尔） 表达式根据表面法线与摄像机方向的标量积来计算衰减。当表面法线正对着摄像机时，输出值为0。当表面法线垂直于摄像机时，输出值为1。结果限制在[0,1]范围内，以确保不会在中央产生任何负颜色。
- GIReplace（GI 替换） 允许美工指定另一个表达式链（通常较为简单），以便在材质用于GI时使用。
- LightmassReplace（光照系统替换） 表达式用来在编译材质以用于正常渲染用途时传递“实时”（Realtime）输入，并在导出材质到光照系统以用于全局照明时传递“光照系统”（Lightmass）输入。使用此表达式可以避免使用导出版本无法正确处理的材质表达式，例如“全局位置”（WorldPosition）。
- LinearInterpolate（线性插值） 表达式根据用作蒙版的第三个输入值，在两个输入值之间进行混合。
- Noise（噪点） 表达式建立过程式噪点场，以使您能够控制其生成方式。
- Previous Frame Switch（上一帧开关） 材质表达式使您能够支持材质中实现的复杂顶点动画 生成正确的运动矢量，这样它们才能正确使用临时AA和动态模糊。
- QualitySwitch（质量开关）表达式允许根据引擎在不同质量级别之间的切换使用不同的表达式网络，例如在较低端的设备上使用较低的质量。
- RotateAboutAxis（绕轴旋转） 表达式在给定旋转轴、该轴上的某个点以及旋转角度的情况下，旋转三通道矢量输入。此表达式适合于使用“全局位置偏移”（WorldPositionOffset）产生质量优于简单剪切的动画。
- SphereMask（球体蒙版） 表达式根据距离计算来输出蒙版值。如果某一个输出是某个点的位置，而另一输入是具有某半径的球体的中心，那么蒙版值将是0（位于球体外部）和1（位于球体内部），并存在一定的过渡区域。此表达式可作用于单分量、双分量、三分量和四分量矢量。
- 薄半透明材质输出 表达式可在单通道中精准再现基于物理的半透明材质。它可用于创建 真正的 染色或彩色半透明材质并对光照和着色做出精准的反馈。
- Vector Noise Material（矢量噪点材质）表达式添加了更多的三维或四维矢量噪点结果以在材质中使用。由于这些函数会产生运行时间开销，建议在使用它们开发外观之后，使用虚幻引擎4.13及其后续版本中引入的绘制材料以渲染目标蓝图 功能将所有或部分计算烘焙到纹理中。

### 1.17. M_Vector 矢量表达式
输出位置、法线等矢量值的表达式。

- ActorPositionWS 输出矢量3(RGB)数据，该数据表示对象在世界场景空间中的位置以及其上的材质。
- CameraWorldPosition 表达式输出三信道矢量值，该值表示摄像机在世界场景空间中的位置。
- CameraVector 表达式输出一个三信道矢量值，该值表示摄像机相对于表面的方向，即像素到摄像机的方向。
- Constant2Vector（常量 2 矢量）表达式输出双通道矢量值，即输出两个常量数值。
- Constant3Vector（常量 3 矢量）表达式输出三通道矢量值，即输出三个常量数值。您可以将 RGB 颜色看作 Constant3Vector（常量 3 矢量），其中每个通道都被赋予一种颜色（红色、绿色、蓝色）。
- Constant4Vector（常量 4 矢量）表达式输出四通道矢量值，即输出四个常量数值。您可以将 RGBA 颜色看作 Constant4Vector（常量 4 矢量），其中每个通道都被赋予一种颜色（红色、绿色、蓝色、alpha）。
- Object Bounds（对象边界） 表达式输出对象在每个轴中的大小。如果用颜色表示，X轴、Y轴、Z轴分别对应于R、G、B。
- ObjectOrientation 表达式输出对象的世界场景向上矢量。换言之，对象的局部正z轴正指向此方向。
- ObjectPositionWS 表达式输出对象边界的世界场景空间中心位置。例如，这对于为植物创建球形照明很有用。
- ParticlePositionWS（粒子位置WS） 表达式输出代表世界场景空间中每个单独粒子位置的Vector3(RGB)数据。
- PixelNormalWS 表达式根据当前法线输出矢量数据，该数据表示像素所面对的方向。
- Pre-Skinned Local Normal（预蒙皮局部法线） 矢量表达式输出一个三信道矢量值，该值表示骨架网格体和静态网格体的局部表面法线。这让您能够实现局部对齐的三平面 材质以及在材质中实现网格体对齐效果。
- Pre-Skinned Local Position（预蒙皮局部位置） 矢量表达式输出一个三信道矢量值，该值允许访问骨架网格体的默认姿势位置以便在每个顶点 输出中使用。这使您能够在动画角色上获得局部化效果。该矢量表达式也可用于静态网格体，它将返回 标准局部位置。
- ReflectionVectorWS 表达式在本质上类似于CameraVectorWS ，但它输出一个三信道矢量值，该值表示通过表面法线反射的摄像机方向。
- VertexNormalWS 表达式输出世界场景空间顶点法线。它只能用于在顶点着色器中执行的材质输入，例如WorldPositionOffset。该表达式对于设置网格体增大或缩小很有用。请注意，沿法线偏移位置会导致几何图形沿UV缝隙拆分。
- Vector Noise Material（矢量噪点材质）

### 1.18. M_VectorOperation 矢量操作表达式
对矢量输入值执行操作的表达式。

- AppendVector（追加矢量）表达式允许您将通道组合在一起，以创建通道数比原始矢量更多的矢量。例如，您可以使用两个 常量 值并进行追加，以建立双通道 Constant2Vector（常量 2 矢量） 值。这有助于将单个纹理中的通道重新排序，或者将多个灰阶纹理组合成一个 RGB 彩色纹理。
- ComponentMask（分量蒙版）表达式允许从输入中选择通道（R、G、B 和/或 A）的特定子集以传递到输出。尝试传递输入中不存在的通道将导致错误，除非输入是单个常量值。在这种情况下，会将单个值传递到每个通道。选择传递的当前通道将显示在表达式的标题栏中。
- CrossProduct 表达式计算两个三通道矢量值输入的交叉乘积，并输出产生的三通道矢量值。假定空间中有两个矢量，则交叉乘积是一个同时垂直于两个输入的矢量。
- DeriveNormalZ（派生法线 Z）表达式在给定 X 和 Y 分量的情况下派生切线空间法线的 Z 分量，并输出所产生的三通道切线空间法线。Z 计算方法为：Z = sqrt(1 - (x * x + y * y))；
- DotProduct 表达式计算点积，点积可以描述为一个矢量投影到另一个矢量上的长度，也可以描述为两个矢量之间的余弦乘以它们的幅值。许多技术使用这种算法来计算衰减。DotProduct要求两个矢量输入具有相同数量的通道。
- Normalize 表达式计算并输出其输入的归一化值。归一化矢量（也称“单位矢量”）的整体长度为1.0。这意味着输入的每个分量都除以矢量的总大小（长度）。
- Transform（转换）表达式将三通道矢量值从一种参考坐标系转换到另一种参考坐标系。

## 999. 引用
官方文档 https://docs.unrealengine.com/zh-CN/Engine/Rendering/Materials/index.html