# UE4_Materials
caidu UE4.25材质
2020-06-18
:toc:

## 1. Content/Materials 材质表达式

### 1.1. 光照半透明？

### 1.2. M_AtmosphericFogColor 大气表达式
用来在全局空间中的任意位置，查询关卡的大气雾的当前颜色。如果没有向其输送全局位置，那么将使用相关像素的全局位置。这在您需要让材质逐渐融入远方的雾颜色时非常有用。

### 1.3. M_Color 颜色表达式
对颜色输入执行操作的表达式。
- Desaturation（去饱和度） 表达式对其输入进行去饱和，即根据特定百分比将其输入的颜色转换为灰色阴影。

### 1.4. M_Constant 常量表达式
输出值在编辑器中设置后或在游戏开始时设置后通常保持不变的表达式。

- Constant（常量）表达式输出单个浮点值。这是最常用的表达式之一，并可连接到任何输入，而不必考虑该输入所需的通道数。例如，如果您将一个常量连接到需要 3 个矢量的输入，那么该常量值将用于全部 3 个元素。提供单个数值时，使用说明区域中的小三角形图标来折叠节点可能非常有用。
- Constant2Vector（常量 2 矢量）表达式输出双通道矢量值，即输出两个常量数值。
- Constant3Vector（常量 3 矢量）表达式输出三通道矢量值，即输出三个常量数值。您可以将 RGB 颜色看作 Constant3Vector（常量 3 矢量），其中每个通道都被赋予一种颜色（红色、绿色、蓝色）。
- Constant4Vector（常量 4 矢量）表达式输出四通道矢量值，即输出四个常量数值。您可以将 RGBA 颜色看作 Constant4Vector（常量 4 矢量），其中每个通道都被赋予一种颜色（红色、绿色、蓝色、alpha）。
- DistanceCullFade（距离剔除消退） 表达式输出一个从黑色逐渐消退到白色的标量值，并可用于使对象进入剔除距离后逐渐消退。请注意，它不会使对象淡出。
- ParticleColor（粒子颜色） 表达式绑定到给定粒子的当前颜色。这必须插入到适当的信道（自发光颜色）。基于在 级联（Cascade粒子系统） 中定义的任何每粒子颜色数据
- ParticleDirection（粒子方向） 表达式逐个粒子输出Vector3(RGB)数据，表示给定粒子当前运动的方向。
- ParticleMotionBlurFade（粒子动态模糊淡出） 表达式输出一个值，该值表示由于动态模糊导致的粒子上的淡出量。值为1表示无模糊，黑色代表完全模糊。
- ParticleRadius（粒子半径） 表达式单独输出每个粒子的半径（采用虚幻单位）。例如，一旦半径达到某个点，就可以对材质进行更改。
- ParticleRelativeTime（粒子相对时间） 表达式输出0到1之间的数字，表示粒子的年龄，0表示出生时刻，1表示死亡时刻。
- Particle Size（粒子大小） 表达式输出粒子sprite的X和Y大小。这可以用来驱动材质的某些方面。
- ParticleSpeed（粒子速度） 输出正在运动的每个粒子的当前速度，单位为每秒虚幻单位。
- PerInstanceFadeAmount（按实例消退量）表达式输出一个浮点值，该值与应用于实例化静态网格（例如植物叶子）的消退量相关联。它是常量，但对于网格的每个实例，可以是不同的数值。
- PerInstanceRandom（按实例随机）表达式按材质所应用于的静态网格实例输出不同的随机浮点值。InstancedStaticMeshComponent（实例化静态网格组件）用于为实例设置随机浮点值，这个值将公开，以便可用于任何期望的内容（例如，窗外的随机光照水平）。它是常量，但对于网格的每个实例有所不同。
- Time（时间）节点用来向材质（例如，Panner（平移） 、Cosine（余弦） 或其他时间相关操作）添加经历时间。
- TwoSidedSign（双面符号）表达式适合在双面定制照明材质的背面翻转法线，以便与冯氏（Phong）明暗处理算法匹配。+1 表示双面材质的正面，-1 表示背面。
- VertexColor（顶点颜色）表达式是材质的访问点，用于访问影响精灵粒子发射器的颜色模块的输出。
- ViewProperty（视图属性） 表达式输出依赖于视图的常量属性，例如视野或渲染目标大小。要访问的视图属性可配置，并且，输出类型取决于所配置的待访问属性。
- PrecomputedAOMask（预先计算的 AO 蒙版）节点用来访问材质中光照系统计算的环境光遮蔽 (AO)， 这可能很适合于过程式纹理贴图，或者在老化效果及尘埃随时间推移而缓慢积累的区域加入老化效果及尘埃。

### 1.5. M_Coordinates 坐标表达式
对纹理坐标、可用作纹理坐标的输出值或者用来修改纹理坐标的输出值执行操作的表达式。

- ActorPositionWS 输出矢量3(RGB)数据，该数据表示对象在世界场景空间中的位置以及其上的材质。
- CameraWorldPosition 表达式输出三信道矢量值，该值表示摄像机在世界场景空间中的位置。
- LightmapUVs（光照贴图 UV）表达式以双通道矢量值形式输出光照贴图 UV 纹理坐标。如果无法获得光照贴图 UV，那么将输出双通道矢量值 (0,0)。
- ObjectOrientation 表达式输出对象的世界场景向上矢量。换言之，对象的局部正z轴正指向此方向。
- ObjectPositionWS 表达式输出对象边界的世界场景空间中心位置。例如，这对于为植物创建球形照明很有用。
- ObjectRadius（对象半径）输出给定对象以 Unreal 单位计的半径值。系统会对比例缩放加以考虑，并且对于每个对象，结果可能是唯一的。
- Panner（平移）表达式输出可用于创建平移（或移动）纹理的 UV 纹理坐标。
- 粒子位置WS（ParticlePositionWS） 表达式输出代表世界场景空间中每个单独粒子位置的Vector3(RGB)数据。
- PixelNormalWS 表达式根据当前法线输出矢量数据，该数据表示像素所面对的方向。
- Rotator（旋转）表达式以双通道矢量值形式输出 UV 纹理坐标，该矢量值可用来创建旋转纹理。
- SceneTexelSize（场景纹素大小）表达式允许按纹素大小进行偏移，正如您使用 SceneColor（场景颜色）
- SceneDepth（场景深度）表达式时执行的偏移操作。这对于在多分辨率系统中检测边缘十分有用，因为不进行此计算时，您就必须使用较小的静态值，从而导致分辨率较低时结果不一致。
- ScreenPosition（屏幕位置）表达式输出当前所渲染像素的屏幕空间位置。
- TextureCoordinate（纹理坐标）表达式以双通道矢量值形式输出 UV 纹理坐标，从而允许材质使用不同的 UV 通道、指定平铺以及以其他方式对网格的 UV 执行操作。
- VertexNormalWS 表达式输出世界场景空间顶点法线。它只能用于在顶点着色器中执行的材质输入，例如WorldPositionOffset。该表达式对于设置网格体增大或缩小很有用。请注意，沿法线偏移位置会导致几何图形沿UV缝隙拆分。
- ViewSize（视图大小）表达式输出一个 2D 矢量，以给出当前视图的大小（以像素为单位）。这对于使材质根据当前屏幕分辨率产生各种变化来说非常有用。
- WorldPosition（全局位置）表达式输出当前像素在全局空间中的位置。要实现可视化，只需将输出连接到“自发光”（Emissive）

### 1.6. M_Depth 深度表达式
处理所渲染像素的深度的表达式。

- DepthFade（深度消退）表达式用来隐藏半透明对象与不透明对象相交时出现的不美观接缝。
- PixelDepth（像素深度）表达式输出当前所渲染像素的深度，即从摄像机开始计算的距离。
- SceneDepth（场景深度）表达式输出现有的场景深度。这类似于 PixelDepth（像素深度） ，但是 PixelDepth（像素深度）只能在当前所绘制像素处进行深度取样，而 SceneDepth（场景深度）可以在 任何位置 进行深度取样。只有半透明材质可以利用 SceneDepth（场景深度）。

### 1.7. M_Custom 自定义表达式
允许您编写自定义 HLSL 着色器代码，这些代码可对任意数量的输入执行操作，并输出操作结果。

### 1.8. M_Font 字体表达式
对字体资产进行取样和输出的表达式。
- FontSample（字体取样）表达式允许您以常规 2D 纹理形式，从字体资源中取得纹理页面样本。字体的阿尔法通道将包含字体轮廓值。您只能指定有效的字体页面。
- FontSampleParameter（字体取样参数）表达式提供了一种在材质实例常量中公开基于字体的参数的方法，这使您可以在不同实例中轻松使用不同的字体。字体的阿尔法通道将包含字体轮廓值。您只能指定有效的字体页面。

## 999. 引用
官方文档 https://docs.unrealengine.com/zh-CN/Engine/Rendering/Materials/index.html